resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:
- job: Android
  strategy:
    matrix:
      Linux:
        imageName: "ubuntu-16.04"
        conanBuildOS: "Linux"
      Windows:
        imageName: "windows-2019"
        conanBuildOS: "Windows"
  pool:
    vmImage: '$(imageName)'
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_OS: "Android",
        CONAN_BASE_PROFILE_OS_API: "21",
        CONAN_BASE_PROFILE_ARCH: "armv7",
        CONAN_BASE_PROFILE_OSBUILD: "$(conanBuildOS)",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "clang",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "6.0",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libc++",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }

- job: Linux
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE_OS: "Linux",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Linux",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "gcc",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "5",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libstdc++",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }

- job: Windows
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "vs2017-win2016"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE_OS: "Windows",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Windows",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "Visual Studio",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "15",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }
      
- job: Macos
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "macOS-10.14"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE_OS: "Macos",
        CONAN_BASE_PROFILE_OS_VERSION: "10.14",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Macos",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "apple-clang",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "10.0",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libc++",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }
      
- job: iOS
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "macOS-10.14"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE_OS: "iOS",
        CONAN_BASE_PROFILE_OS_VERSION: "12.0",
        CONAN_BASE_PROFILE_ARCH: "armv8",
        CONAN_BASE_PROFILE_OSBUILD: "Macos",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "apple-clang",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "10.0",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libc++",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }
    
- job: Upload
  dependsOn:
  - Android
  - Linux
  - Windows
  - Macos
  - iOS
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: uploadConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_UPLOAD: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_LOGIN_USERNAME: "tereius",
        CONAN_PASSWORD: "$(secret)",
      }
