resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:
- job: Android
  strategy:
    matrix:
      armv7Linux:
        imageName: "ubuntu-18.04"
        buildProfile: "androidArmv7LinuxHost"
      armv8Linux:
        imageName: "ubuntu-18.04"
        buildProfile: "androidArmv8LinuxHost"
      x86Linux:
        imageName: "ubuntu-18.04"
        buildProfile: "androidx86LinuxHost"
      x86_64Linux:
        imageName: "ubuntu-18.04"
        buildProfile: "androidx86_64LinuxHost"
      armv7Windows:
        imageName: "windows-2019"
        buildProfile: "androidArmv7WinHost"
      armv8Windows:
        imageName: "windows-2019"
        buildProfile: "androidArmv8WinHost"
      x86Windows:
        imageName: "windows-2019"
        buildProfile: "androidx86WinHost"
      x86_64Windows:
        imageName: "windows-2019"
        buildProfile: "androidx86_64WinHost"
  pool:
    vmImage: '$(imageName)'
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_PATH: "./buildProfiles/$(buildProfile).profile",
        CONAN_BUILD_PROFILE: "default",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }

- job: Raspbian
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "ubuntu-18.04"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE_PATH: "./buildProfiles/raspbian.profile",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtwebsockets=True"
      }
      
- job: Linux
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "ubuntu-18.04"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE: "default",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }

- job: Windows
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "windows-2019"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE: "default",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }
      
- job: Macos
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "macOS-11"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "$(buildType)",
        CONAN_BASE_PROFILE: "default",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtmultimedia=True,Qt:qtxmlpatterns=True,Qt:qtdoc=True,Qt:qtlocation=True,Qt:qtsensors=True,Qt:qtconnectivity=True,Qt:qtimageformats=True,Qt:qtx11extras=True,Qt:qtwebsockets=True"
      }
      
- job: Emscripten
  strategy:
    matrix:
      Debug:
        buildType: "Debug"
      Release:
        buildType: "Release"
  pool:
    vmImage: "ubuntu-18.04"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_PATH: "./buildProfiles/emscripten.profile",
        CONAN_BUILD_PROFILE: "default",
        CONAN_OPTIONS: "Qt:GUI=True,Qt:widgets=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt:qtquickcontrols=True,Qt:qtimageformats=True"
      }
    
- job: Upload
  dependsOn:
  - Android
  - Linux
  - Windows
  - Macos
  - Emscripten
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: uploadConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_UPLOAD: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_LOGIN_USERNAME: "ci",
        CONAN_PASSWORD: "$(secret)",
      }
