resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:      
- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 120
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_OS: "Linux",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Linux",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "gcc",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "5",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libstdc++",
        CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:widgets=True,Qt:openssl=True,Qt:qtbase=True,Qt:qtsvg=True,Qt:qtdeclarative=True,Qt:qttools=True,Qt:qttranslations=True,Qt:qtgraphicaleffects=True,Qt:qtquickcontrols2=True,Qt::qtquickcontrols=True,Qt:qtmultimedia=True,Qt::qtxmlpatterns=True,Qt::qtdoc=True,Qt::qtlocation=True,Qt::qtsensors=True,Qt::qtconnectivity=True,Qt::qtimageformats=True,Qt::qtx11extras=True,Qt::qtwebsockets=True"
      }
    
- job: Upload
  dependsOn:
  - Linux
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: uploadConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_UPLOAD: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_LOGIN_USERNAME: "tereius",
        CONAN_PASSWORD: "$(secret)",
      }
