resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      ref: dev
      endpoint: Tereius

jobs:
  - job: Android
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: 0
    steps:
      - template: buildConanRecipe.yml@templates
        parameters:
          conanEnv:
            {
              CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:opengl=desktop,Qt:qtbase=True,Qt:widgets=True,Qt:qtdeclarative=True,Qt:qtsvg=True",
              CONAN_HOST_PROFILE_PATH: "./hostProfiles/androidArmv7.profile",
              CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
            }

  - job: Linux
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: 0
    steps:
      - template: buildConanRecipe.yml@templates
        parameters:
          conanEnv:
            {
              CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:opengl=desktop,Qt:qtbase=True,Qt:widgets=True,Qt:qtdeclarative=True,Qt:qtsvg=True",
              CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
            }

  - job: Windows
    pool:
      vmImage: "windows-2019"
    timeoutInMinutes: 0
    steps:
      - template: buildConanRecipe.yml@templates
        parameters:
          conanEnv:
            {
              CONAN_OPTIONS: "Qt:shared=True,Qt:GUI=True,Qt:opengl=desktop,Qt:qtbase=True,Qt:widgets=True,Qt:qtdeclarative=True,Qt:qtsvg=True",
              CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
            }

  - job: Upload
    dependsOn:
      - Android
      - Linux
      - Windows
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: uploadConanRecipe.yml@templates
        parameters:
          conanEnv:
            {
              CONAN_UPLOAD: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
              CONAN_LOGIN_USERNAME: "ci",
              CONAN_PASSWORD: "$(secret)",
            }
