[settings]
os=Android
os.api_level=28
arch=x86
compiler=clang
compiler.version=18
compiler.libcxx=c++_shared
build_type=Release
[options]
qt/*:opengl=es2
[tool_requires]
cmake/3.23.5
android-ndk/r27c@de.privatehive/stable
android-sdk/latest@de.privatehive/stable
openjdk/17.0.14@de.privatehive/stable
