[settings]
os=iOS
os.version=18.5
os.sdk=iphoneos
os.sdk_version=18.5
arch=armv8
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=17
build_type=Release
[options]
shared=False
[tool_requires]
cmake/3.23.5
