[settings]
os=Linux
arch=armv6
compiler=gcc
compiler.version=13.1
compiler.libcxx=libstdc++11
build_type=Release
[options]
qt/*:opengl=es2
[tool_requires]
cmake/3.23.5
raspberry-pi-toolchain/bullseye@de.privatehive/stable
