[settings]
os=Emscripten
arch=wasm
compiler=clang
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
arch_build=x86_64
os_build=Linux
[options]
Qt:opengl=es2
[build_requires]
emsdk/1.39.8@tereius/stable
[env] 
