name: "Create Conan Package"
on: push

jobs:
  create:
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@317da1289dfbe39e6aec4875a76c83aecdbe2600
    with:
      runs-on: self-hosted
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
      conan_options: "qt/*:shared=True,qt/*:GUI=True,qt/*:opengl=desktop,qt/*:qtbase=True,qt/*:widgets=True,qt/*:qtdeclarative=True,qt/*:qtsvg=True"
